### ISSUE TITLE
cssh AttributeError: 'Server' object has no attribute 'serve_forever'

### ISSUE THREAD

**Issue by henrebotha** [ms-jpq/isomorphic_copy#1]
# Reproduction

## Steps taken

1. Clone repo to `~/isomorphic-copy`.
2. Prepend repo `/bin` path to env.
3. Start new shell.
4. `cssh cron.dev`

## Expected result

I ssh into the host `cron.dev`.

## Observed result

I get this error, looping over and over.

```
ssh cron.dev sh -c $HOME/isomorphic-copy/bin/csshd
Traceback (most recent call last):
  File "/home/hbotha/isomorphic-copy/isomorphic-cp", line 251, in <module>
    loop.run_until_complete(main())
  File "/opt/blue-python/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/hbotha/isomorphic-copy/isomorphic-cp", line 239, in main
    await csshd()
  File "/home/hbotha/isomorphic-copy/isomorphic-cp", line 207, in csshd
    await server.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
```

# System

* zsh 5.7.1 (x86_64-ubuntu-linux-gnu)
* Python 3.7.5 (at `/usr/bin/python3`)

**Comment by ms-jpq** [comment]
Oh god its python 3.6. 

I will see what I can do, hopefully it wont require me to rewrite too much

**Comment by ms-jpq** [comment]
@henrebotha Ok i fixed it. Please do a git pull on both local and remote :D

**Comment by henrebotha** [comment]
Error is gone! Thanks for the quick work.
