### ISSUE TITLE
No getenv

### ISSUE THREAD

**Issue by j-hui** [ms-jpq/isomorphic_copy#3]
The nvim snippet doesn't seem to work:
```
Error detected while processing /home/jhui/.vimrc:
line   65:
E117: Unknown function: getenv
E15: Invalid expression: getenv('DISPLAY') == v:null
Press ENTER or type command to continue
```
This also doesn't seem to work for vim. I have the repo cloned and the `bin` directory added to my `PATH` on both ends, and am accessing a dev server using `ssh` while the `cssh` connection is running in another terminal session.

**Comment by ms-jpq** [comment]
hi there,

which version of vim are you using?

![图片](https://user-images.githubusercontent.com/50598611/86451206-6d866d80-bccf-11ea-838d-7ae83d34d648.png)

I only tested in VIM 8, so it is possible an older version of VIM would not have this function. 

I can try and figure out how to make it work if I can have your version though

**Comment by j-hui** [comment]
Sorry for the delay. I was using Neovim v0.4.3.

With regular vim, it just doesn't work (although the snippet doesn't fail).

Unfortunately I'm probably not going to use this utility ): when I put `isomorphic-copy/bin/` in my `PATH`, yanking and putting in Neovim also seems to break---when doing `yyp`, instead of putting to the next line, it will paste right after the cursor.

**Comment by ms-jpq** [comment]
Oh good catch.

I just pushed a fix here https://github.com/ms-jpq/isomorphic-copy/commit/31186063f311aa8db6262fbb6e499e0cefdcee20,

Please do a `git pull` on all of your repos.

I originally stripped out all of the trailing newlines beacuse I thought that was a good idea at the time, reverted it.
